### ISSUE TITLE
[DEV] oracle implementation (based on psq/stacks-open-oracle)

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#25]
https://github.com/psq/stacks-open-oracle, at least until we have Chainlink

**Comment by hyossid** [comment]
I have done for making an oracle interface contract for mocking but have some questions.

**Question and concern :**
1. Collateral Rebalancing Pool fetches price from oracle, but also from yield token pool and determine (strike, vol). However, price of each token in the pool is determined by equation (AMM). Then how do you make a usage of fetched price from oracle in collateral rebalancing pool?

2. I am trying to do the mock oracle, which we have to manually feed the price data. But since the stacks-open-oracle is not even available in RegTest, I am wondering whether we should copy and deploy stacks-open-oracle.... Following is what I got from Pascal regarding my inquiry implementing oracle before testnet. 

_psq — 07/26/2021
I'd create a stub contract instead of deploying the oracle and then feeding it some data.  I tend to think that's beyond what clarinet is meant to help with
then again, the oracle contract has no dependencies, and adding a bit of data would just be a matter of calling add-price with the right bytes (that's the rub)
you do have some examples at https://github.com/psq/stacks-open-oracle/blob/master/test/unit/test-oracle.js#L91, so you could create an other contract, deployed after the oracle, that makes a few calls to add-price with this data during its initialization
seems a stub is the easier route, though_
